### ISSUE TITLE
Broken in 10.5.0 again

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-plugin-fanart#12]
```
[21:32:51] [ERR] [15] ProviderManager: SeasonProvider failed in GetImageInfos for type Season
System.MissingMethodException: Method not found: 'System.String MediaBrowser.Model.Extensions.StringHelper.Replace(System.String, System.String, System.String, System.StringComparison)'.
   at Jellyfin.Plugin.Fanart.Providers.SeasonProvider.<>c__DisplayClass12_0.<PopulateImages>b__0(Image i)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Jellyfin.Plugin.Fanart.Providers.SeasonProvider.PopulateImages(List`1 list, List`1 images, ImageType type, Int32 width, Int32 height, Int32 seasonNumber)
   at Jellyfin.Plugin.Fanart.Providers.SeasonProvider.AddImages(List`1 list, RootObject obj, Int32 seasonNumber, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.SeasonProvider.AddImages(List`1 list, Int32 seasonNumber, String path, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.SeasonProvider.GetImages(BaseItem item, CancellationToken cancellationToken)       at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, CancellationToken cancellationToken, IRemoteImageProvider provider, List`1 preferredLanguages, Nullable`1 type)
```

**Comment by Bond-009** [comment]
Updating to netstandard2.1 should fix that, but breaks compatibility with older jellyfin versions

**Comment by ThatNerdyPikachu** [comment]
@Bond-009 Does the latest published version work on stable, or should I keep using my 2.1 build?

**Comment by Bond-009** [comment]
Hasn't been updated yet.

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/issues/2574

**Comment by bwaddington** [comment]
doesnt seem to be working in 10.5.2

**Comment by samwathegreat** [comment]
My 10.5.0 system crashed when this plugin auto-updated.  This is the second time I've had a plugin update crash my system.  I really want to turn off auto updates for plugins.  They shouldn't be able to crash the system -- rather they should fail gracefully if there is an issue.

The log files indicate the plugin in directly responsible :

![image](https://user-images.githubusercontent.com/4813336/78102954-9d189780-73b9-11ea-935e-eed8065b160c.png)

**Comment by ThatNerdyPikachu** [comment]
I installed the plugin (v4), and my nightly server crashed. I then restarted it, it crashes.

```
[00:37:27] [INF] [17] Emby.Server.Implementations.Updates.InstallationManager: New plugin installed: Fanart 4.0.0.0 Rel
ease
[00:37:28] [INF] [17] App: App needs to be restarted.
[00:37:28] [WRN] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to 192.168.1.198. Time
 (slow): 0:00:00.9743364. http://192.168.1.171:8096/Packages/Installed/Fanart?updateClass=Release&AssemblyGuid=170a157f
-ac6c-437a-abdd-ca9c25cebd39&version=4.0.0.0
[00:37:27] [FTL] [29] Main: Unhandled Exception
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutra
l, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.<>c.<PluginInstalled>b__249_0(Assembly x)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Emby.Server.Implementations.ApplicationHost.PluginInstalled(Object sender, GenericEventArgs`1 args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 call
back, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.
5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.<>c.<PluginInstalled>b__249_0(Assembly x)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at Emby.Server.Implementations.ApplicationHost.PluginInstalled(Object sender, GenericEventArgs`1 args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 call
back, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


[00:38:24] [INF] [1] Main: Jellyfin version: 10.5.0
[00:38:24] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache", "--ffm
peg", "/usr/local/bin/ffmpeg"]
[00:38:24] [INF] [1] Main: Operating system: Linux
[00:38:24] [INF] [1] Main: Architecture: X64
[00:38:24] [INF] [1] Main: 64-Bit Process: True
[00:38:24] [INF] [1] Main: User Interactive: True
[00:38:24] [INF] [1] Main: Processor count: 2
[00:38:24] [INF] [1] Main: Program data path: /config
[00:38:24] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[00:38:24] [INF] [1] Main: Application directory: /jellyfin/
[00:38:25] [INF] [1] ServerConfigurationManager: Setting cache path: /cache
[00:38:25] [INF] [1] App: Loading assemblies
[00:38:25] [INF] [1] App: Loaded assembly Jellyfin.Plugin.Fanart, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null
 from /config/plugins/Fanart/Jellyfin.Plugin.Fanart.dll
[00:38:25] [FTL] [1] Main: Error while starting server.
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutra
l, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)

[00:38:25] [INF] [1] App: Disposing CoreAppHost
[00:38:25] [FTL] [1] Main: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
   at Emby.Server.Implementations.ApplicationHost.Dispose()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
   at Emby.Server.Implementations.ApplicationHost.Dispose()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
```

**Comment by ThatNerdyPikachu** [comment]
@Bond-009 It doesn't crash the server now, but now the plugin fails to load on master (latest plugin build from repo):

```
[01:16:12] [INF] [1] App: Loaded assembly Jellyfin.Plugin.Fanart, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null
 from /config/plugins/Fanart/Jellyfin.Plugin.Fanart.dll
[01:16:12] [ERR] [1] App: Error getting exported types from Jellyfin.Plugin.Fanart, Version=4.0.0.0, Culture=neutral, P
ublicKeyToken=null
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutra
l, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
```

**Comment by Artiume** [comment]
The graceful failing should be thanks to this 

https://github.com/jellyfin/jellyfin/pull/2730

**Comment by ThatNerdyPikachu** [comment]
What's causing it to be unsupported though? Did something change in master relating to plugins?

**Comment by Artiume** [comment]
We're reworking on the plugins interact with the server. while we do this rework, it's going to cause issues. @dkanada could explain in more detail but it's just the nature of the game until we get the system to the point where we want it.

**Comment by Bond-009** [comment]
Nightly is still tagged as 10.5.0, plugins built for 10.5.2 will fail to load

**Comment by ThatNerdyPikachu** [comment]
@Bond-009 How would I change the plugins Jellyfin version to 10.5.0? I don't see anything that controls this anywhere in the repo, am I missing something obvious?

**Comment by Bond-009** [comment]
https://github.com/jellyfin/jellyfin-plugin-fanart/blob/master/Jellyfin.Plugin.Fanart/Jellyfin.Plugin.Fanart.csproj#L12
This takes the latest version, you can change it to 10.5.0

**Comment by samwathegreat** [comment]
> @Bond-009 How would I change the plugins Jellyfin version to 10.5.0? I don't see anything that controls this anywhere in the repo, am I missing something obvious?

Why don't you just update your jellyfin install instead of altering a plugin to work on an older version of jellyfin?

**Comment by Bond-009** [comment]
@samwathegreat He is running nightly
