### ISSUE TITLE
fanart plugin errors out when fetching logos

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-plugin-fanart#24]
Hey,

I decided to try fetch logos for all movies now that they are properly displayed and used in the ui, but I can't seem to get the plugin to successfully fetch all the missing data. Identifying things manually works every time, but the "Replace all" and "Replace missing" only seem to download a few, and then fail the rest. Again, Identifying things manually after the process has completed works fine.

For some more info: [reddit](https://www.reddit.com/r/jellyfin/comments/mcygr1/metadata_question/)

Many of these errors are logged while the process is running:

```[07:37:07] [ERR] [235] MediaBrowser.Providers.Movies.MovieMetadataService: Error in Fanart
System.ArgumentException: Unable to determine image file extension from mime type text/html
   at MediaBrowser.Providers.Manager.ImageSaver.GetStandardSavePath(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.GetSavePaths(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadImage(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, ImageType type, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadImage(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, ImageType type, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, Int32 backdropLimit, Int32 screenshotLimit, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)```

Might some rate limiting that's not handled in the plugin but not sure.

Jellyfin version is 10.7.1

**Comment by mochman** [comment]
I have the same error using Jellyfin version 10.7.5.
```
[2021-06-07 09:20:35.944 +00:00] [ERR] Error in "Fanart"
System.ArgumentException: Unable to determine image file extension from mime type text/html
   at MediaBrowser.Providers.Manager.ImageSaver.GetStandardSavePath(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.GetSavePaths(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadBackdrops(BaseItem item, LibraryOptions libraryOptions, ImageType imageType, Int32 limit, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadBackdrops(BaseItem item, LibraryOptions libraryOptions, ImageType imageType, Int32 limit, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, Int32 backdropLimit, Int32 screenshotLimit, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
```

**Comment by michaelkrieger** [comment]
Same issue in 10.7.7

```
jellyfin              | [00:45:30] [ERR] [9] MediaBrowser.Providers.Movies.MovieMetadataService: Error in Fanart
jellyfin              | System.ArgumentException: Unable to determine image file extension from mime type text/html
jellyfin              |    at MediaBrowser.Providers.Manager.ImageSaver.GetStandardSavePath(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
jellyfin              |    at MediaBrowser.Providers.Manager.ImageSaver.GetSavePaths(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
jellyfin              |    at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
jellyfin              |    at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadBackdrops(BaseItem item, LibraryOptions libraryOptions, ImageType imageType, Int32 limit, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, CancellationToken cancellationToken)
jellyfin              |    at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadBackdrops(BaseItem item, LibraryOptions libraryOptions, ImageType imageType, Int32 limit, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, CancellationToken cancellationToken)
jellyfin              |    at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, Int32 backdropLimit, Int32 screenshotLimit, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)
```

**Comment by markalex2209** [comment]
Is this error still present, and if so what are exact steps to reproduce?
